name: Build android apk on dispath
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get nodejs(use lts because why not xD)
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install depidencies
        run: npm i --verbose

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup prebuild with expo
        run: npx expo prebuild

      - name: Build the apk(IM STARTING TO LOSE MY MIND)
        run: cd ./android && ./gradlew assembleRelease

      - name: Aight just tell me where r u
        run: ls ./android/app
      - name: Upload apk file to gh artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/*
